# 热部署相关
spring:
  devtools:
    restart:
      enabled: false
foo: application

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
